package com.aztlansoft.namaka.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table DISCOUNT.
 */
public class Discount
{

  private Long id;
  private String name;
  private String detail;
  private String disclosure;
  private String url;
  private String contact;
  private String email;
  private String phone;
  private String address;
  private long categoryId;

  public Discount()
  {
  }

  public Discount(Long id)
  {
    this.id = id;
  }

  public Discount(Long id, String name, String detail, String disclosure, String url, String contact, String email, String phone, String address, long categoryId)
  {
    this.id = id;
    this.name = name;
    this.detail = detail;
    this.disclosure = disclosure;
    this.url = url;
    this.contact = contact;
    this.email = email;
    this.phone = phone;
    this.address = address;
    this.categoryId = categoryId;
  }

  public Long getId()
  {
    return id;
  }

  public void setId(Long id)
  {
    this.id = id;
  }

  public String getName()
  {
    return name;
  }

  public void setName(String name)
  {
    this.name = name;
  }

  public String getDetail()
  {
    return detail;
  }

  public void setDetail(String detail)
  {
    this.detail = detail;
  }

  public String getDisclosure()
  {
    return disclosure;
  }

  public void setDisclosure(String disclosure)
  {
    this.disclosure = disclosure;
  }

  public String getUrl()
  {
    return url;
  }

  public void setUrl(String url)
  {
    this.url = url;
  }

  public String getContact()
  {
    return contact;
  }

  public void setContact(String contact)
  {
    this.contact = contact;
  }

  public String getEmail()
  {
    return email;
  }

  public void setEmail(String email)
  {
    this.email = email;
  }

  public String getPhone()
  {
    return phone;
  }

  public void setPhone(String phone)
  {
    this.phone = phone;
  }

  public String getAddress()
  {
    return address;
  }

  public void setAddress(String address)
  {
    this.address = address;
  }

  public long getCategoryId()
  {
    return categoryId;
  }

  public void setCategoryId(long categoryId)
  {
    this.categoryId = categoryId;
  }

  @Override
  public String toString()
  {
    return this.name;
  }
}
